language: ruby
rvm:
  - 1.9.3
branches:
  only:
    - master
env:
  - REDMINE_VERSION=2.3.3 VERBOSE=yes CODECOV_TOKEN=afbfbb99-5029-45bc-835a-cf39c122d13c
script:
  - export PLUGIN=redmine_remote_git
  - export WORKSPACE=$(pwd)/workspace
  - export PATH_TO_PLUGIN=$(pwd)
  - export PATH_TO_REDMINE=$WORKSPACE/redmine
  - mkdir $WORKSPACE
  - bash -x ./.travis-init.sh -r || exit 1
  - bash -x ./.travis-init.sh -i || exit 1
  - bash -x ./.travis-init.sh -t || exit 1
  - bash -x ./.travis-init.sh -u || exit 1
